# Generated by Django 5.0.6 on 2025-07-07 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-upload_time'], 'verbose_name': '文件', 'verbose_name_plural': '文件管理'},
        ),
    ]
