# Generated by Django 5.0.6 on 2025-07-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_uploadedfile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogdata',
            name='current_1',
            field=models.FloatField(verbose_name='电流1(mA)'),
        ),
        migrations.AlterField(
            model_name='analogdata',
            name='current_2',
            field=models.FloatField(verbose_name='电流2(mA)'),
        ),
    ]
