# Generated by Django 5.0.6 on 2025-08-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_depots_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='direction1_enabled',
            field=models.BooleanField(default=True, verbose_name='一方向启用'),
        ),
        migrations.AddField(
            model_name='device',
            name='direction2_enabled',
            field=models.BooleanField(default=True, verbose_name='二方向启用'),
        ),
    ]
