# 使用官方 Python 镜像作为基础镜像
FROM python:3.10

# 设置工作目录
WORKDIR /app

# 复制当前目录下的所有文件到容器中的工作目录
COPY udp_agent.py requirements.txt /app/

RUN pip install --upgrade pip

# 安装所需的Python包
RUN pip install --no-cache-dir -r requirements.txt

# 开放 UDP 端口，供容器监听
EXPOSE 38315/udp

# 设置容器启动命令，执行 udp_agent.py 脚本
CMD ["python", "udp_agent.py"]
