name: bt_nms_prod

services:
  vue:
    image: my_vue:prod
    container_name: bt_nms_vue_prod0
    user: "101:101"
    ports:
      - "${VUE_PORT:-38173}:8080"
    volumes:
      - ./frontend/nginx.standalone.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend_proxy
    restart: unless-stopped

networks:
  frontend_proxy:
    external: true
    name: bt_nms_frontend_proxy
