# 当前没用到这个文件，后续优化性能可能会用到
# 基础镜像
FROM python:3.12-slim

# 设置工作目录
WORKDIR /app

# 安装必要的系统依赖
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# 安装 Python 依赖
COPY requirements_udp_id_receiver.txt /app/requirements_udp_id_receiver.txt
RUN pip install --no-cache-dir -r /app/requirements_udp_id_receiver.txt

# 设置默认环境变量
ENV PYTHONUNBUFFERED=1
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379

# 启动命令
CMD ["python", "udp_id_receiver.py"]
