"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from django.core.exceptions import ImproperlyConfigured
from consts import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent


def _load_project_root_env():
    env_path = PROJECT_ROOT / ".env"
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def _get_env_list(*names: str):
    values: list[str] = []
    for name in names:
        raw_value = os.getenv(name, "")
        if not raw_value:
            continue
        for item in raw_value.replace(";", ",").split(","):
            item = item.strip()
            if item:
                values.append(item)
    return values


def _get_env_bool(name: str, default: bool = False) -> bool:
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    return raw_value.strip().lower() in {"1", "true", "yes", "on"}


def _get_env_int(name: str, default: int) -> int:
    raw_value = os.getenv(name)
    if raw_value is None or raw_value == "":
        return default
    return int(raw_value)


def _running_tests() -> bool:
    return "test" in sys.argv


def _get_data_dir():
    raw_value = os.getenv("DATA_DIR", "").strip() or "/srv/bt_nms_data"

    path = Path(raw_value)
    if not path.is_absolute():
        path = (PROJECT_ROOT / path).resolve()
    return str(path)


def _get_deploy_host_list():
    deploy_host_file = BASE_DIR / "deploy_host_ip.txt"
    if deploy_host_file.exists():
        raw_lines: list[str] = []
        for raw_line in deploy_host_file.read_text(encoding="utf-8").splitlines():
            line = raw_line.split("#", 1)[0].strip()
            if line:
                raw_lines.append(line)
        if raw_lines:
            file_values = ",".join(raw_lines)
            return [
                item.strip()
                for item in file_values.replace(";", ",").split(",")
                if item.strip()
            ]
    return []


def _build_csrf_trusted_origins(*ports: int):
    origins = {
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "https://localhost:8443",
        "https://127.0.0.1:8443",
        "http://localhost:38173",
        "http://127.0.0.1:38173",
        "https://localhost:38443",
        "https://127.0.0.1:38443",
    }
    for host in _get_deploy_host_list():
        if host.startswith("http://") or host.startswith("https://"):
            origins.add(host.rstrip("/"))
            continue
        for port in ports:
            origins.add(f"https://{host}:{port}")
        for port in ports:
            origins.add(f"http://{host}:{port}")
    return sorted(origins)


_load_project_root_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _get_env_bool("DEBUG", False)
#DEBUG = False #20241218 改成false之后后端admin界面显示不出css样式

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    if DEBUG or _running_tests() or _get_env_bool("DJANGO_ALLOW_INSECURE_DEFAULTS", False):
        SECRET_KEY = "django-insecure-dev-only-change-me"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DEBUG is false.")

AUTH_USER_MODEL = 'myapp.CustomUser' 

ALLOWED_HOSTS = _get_env_list("DJANGO_ALLOWED_HOSTS", "ALLOWED_HOSTS")
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "bt_nms_django_app"]
    if DEBUG or _running_tests():
        ALLOWED_HOSTS.append("testserver")

# Application definition

INSTALLED_APPS = [
    'django_admin_filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # 确保添加此项
    'channels',
    'myapp',
    'django_celery_beat',
    'django_celery_results',  # 添加 Celery 结果后端
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # 可选：仅在需要黑名单功能时添加
    'corsheaders',
    'import_export',
]

SITE_ID = 1  # 默认站点的ID

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',#20241218注释掉，因为前端使用JWT认证，不需要使用CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

USE_LOCAL_TEST_SERVICES = _running_tests() and not _get_env_bool("FNTL_TEST_REAL_SERVICES", False)

if USE_LOCAL_TEST_SERVICES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DATABASE_NAME', 'mydatabase'),
            'USER': os.getenv('DATABASE_USER', 'myuser'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD', ''),
            'HOST': os.getenv('DATABASE_HOST', 'db'),
            'PORT': os.getenv('DATABASE_PORT', '5432'),
        }
    }

# Django发送GET/POST请求的数量限制。一个单独的请求上传数据时，这个设置限制了该请求中允许的最大字段数量。超出这个数量的请求将被拒绝，并抛出 TooManyFieldsSent 异常。
DATA_UPLOAD_MAX_NUMBER_FIELDS = _get_env_int("DATA_UPLOAD_MAX_NUMBER_FIELDS", 5000)


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
#LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Shanghai' 
#TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# 添加语言设置
LANGUAGES = [
    ('zh-hans', 'Simplified Chinese'),
    ('en', 'English'),
]

# 语言文件目录
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DATA_UPLOAD_MAX_MEMORY_SIZE = _get_env_int("DATA_UPLOAD_MAX_MEMORY_SIZE", 50 * 1024 * 1024)
FILE_UPLOAD_MAX_MEMORY_SIZE = _get_env_int("FILE_UPLOAD_MAX_MEMORY_SIZE", 10 * 1024 * 1024)

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
DATA_DIR = _get_data_dir()
CLEANUP_EXPORT_DIR = str(Path(DATA_DIR) / "cleanup_exports")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'#所有新建模型的主键默认使用BigAutoField以防止记录数达到上限导致不能写入新记录

# Redis configuration
REDIS_HOST = os.getenv('REDIS_HOST', 'redis')  # 或者你的Redis服务器地址
#REDIS_HOST = 'localhost'
REDIS_PORT = _get_env_int('REDIS_PORT', 6379)  # Redis默认端
REDIS_DB = _get_env_int('REDIS_DB', 1)
REDIS_BROKER_DB = _get_env_int('REDIS_BROKER_DB', 0)

# 配置 Channels
ASGI_APPLICATION = 'myproject.asgi.application'
if USE_LOCAL_TEST_SERVICES:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [(REDIS_HOST, REDIS_PORT)],
            },
        },
    }

# 配置缓存
if USE_LOCAL_TEST_SERVICES:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'bt-nms-local-test-cache',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}', # 根据你的 Redis 服务器地址和端口进行调整
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }


# 配置 Celery
CELERY_BROKER_URL = 'memory://' if USE_LOCAL_TEST_SERVICES else f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_BROKER_DB}'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_RESULT_BACKEND = 'cache+memory://' if USE_LOCAL_TEST_SERVICES else f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_BROKER_DB}' #CELERY_RESULT_BACKEND = 'django-db'#使用 Django 作为 Celery 结果后端
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
#CELERY_TIMEZONE = 'UTC'
CELERY_TIMEZONE = 'Asia/Shanghai'
##CELERYD_POOL = 'gevent'

#配置Celery_Beat
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,  # Default page size, can be overridden by client
    'PAGE_SIZE_QUERY_PARAM': 'page_size',
    'MAX_PAGE_SIZE': 0,  # Optional: limit the maximum page size
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',#This will ensure that DRF only uses the JSON renderer and does not attempt to render HTML forms.
    ),
}


from datetime import timedelta

# JWT 设置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=_get_env_int("JWT_ACCESS_TOKEN_LIFETIME_DAYS", 1)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=_get_env_int("JWT_REFRESH_TOKEN_LIFETIME_DAYS", 7)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
}

'''
CORS_ALLOWED_ORIGINS = [ # 确保只有授权的前端应用能够访问你的后端 API
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    'http://192.168.31.243:5173' #本机局域网IP地址
]'''
CORS_ALLOWED_ORIGINS = _get_env_list("CORS_ALLOWED_ORIGINS")
if not CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:38173",
        "http://127.0.0.1:38173",
        "https://localhost:38443",
        "https://127.0.0.1:38443",
    ]
CORS_ALLOW_ALL_ORIGINS = _get_env_bool("CORS_ALLOW_ALL_ORIGINS", DEBUG) #跨域 AJAX 请求（浏览器 JS 去调接口）

CSRF_TRUSTED_ORIGINS = _build_csrf_trusted_origins(8000, 8443, 38173, 38443)

SESSION_COOKIE_SECURE = _get_env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = _get_env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "Lax")
SECURE_SSL_REDIRECT = _get_env_bool("SECURE_SSL_REDIRECT", False)
SECURE_HSTS_SECONDS = _get_env_int("SECURE_HSTS_SECONDS", 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _get_env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = _get_env_bool("SECURE_HSTS_PRELOAD", False)
SECURE_CONTENT_TYPE_NOSNIFF = True
