def make_devices(start_serial_id: int, end_serial_id: int, *, nms_offset: int = 0, a1_interval: float = 5.0):
    return [
        {
            "serial_id": serial_id,
            "nms_id": serial_id + nms_offset,
            "a1_interval": a1_interval,
        }
        for serial_id in range(start_serial_id, end_serial_id + 1)
    ]


def make_paired_devices(
    primary_serial_id: int,
    backup_serial_id: int,
    *,
    pair_id,
    nms_offset: int = 0,
    a1_interval: float = 5.0,
):
    return [
        {
            "serial_id": primary_serial_id,
            "nms_id": primary_serial_id + nms_offset,
            "a1_interval": a1_interval,
            "pair_id": str(pair_id),
            "role": "primary",
        },
        {
            "serial_id": backup_serial_id,
            "nms_id": backup_serial_id + nms_offset,
            "a1_interval": a1_interval,
            "pair_id": str(pair_id),
            "role": "backup",
        },
    ]


CONFIG = {
    "agent": {
        "ip": "",
        "name": "",
        "role": "main",
    },
    "redis": {
        "host": "localhost",
        "port": 36380,
        "db": 0,
    },
    "stream": {
        "raw_stream": "sy.raw",
        "raw_stream_maxlen": 200000,
        "cmd_stream": "sy-serial-commands",
        "cmd_group": "sy_agent_cmd_group",
        "cmd_consumer": "sy-agent-1",
        "cmd_block_ms": 1000,
        "cmd_count": 10,
    },
    "cmd": {
        "dlq_stream": "sy-serial-commands.dlq",
        "dlq_maxlen": 50000,
        "done_key_prefix": "sy:cmd_done:",
        "done_ttl_sec": 3600,
        "done_local_ttl_sec": 600,
        "dlq_dedupe_prefix": "sy:cmd_dlq:",
        "dlq_dedupe_ttl_sec": 600,
        "try_key_prefix": "sy:cmd_try:",
        "try_ttl_sec": 3600,
        "max_tries": 20,
        "inflight_ttl_sec": 3.0,
        "no_resp_enable": True,
        "cc_confirm_delay_sec": 0.08,
        "cc_confirm_timeout_sec": 0.25,
        "cc_confirm_a1": True,
        "bb_cmd_retries": 3,
        "no_resp_cmds": ["CC"],
    },
    "time_sync": {
        "enable": False,
        "interval_sec": 3600,
    },
    "a2_burst": {
        "enable": True,
        "max": 3,
        "timeout_sec": 0.08,
        "budget_sec": 0.16,
    },
    "serial": {
        "default_baudrate": 19200,
        "timeout": 0.0,
    },
    "ui": {
        "mode": "dashboard",
        "refresh_sec": 1.0,
        "event_buffer_size": 20,
        "ansi": "auto",
    },
    "debug_tuning": {
        "AFTER_WRITE_SLEEP_SEC": 0.100,
        "ENABLE_AFTER_WRITE_SLEEP": True,
        "WAIT_RESPONSE_TIMEOUT_SEC": 0.20,
        "RX_IDLE_SLEEP_SEC": 0.002,
        "AUTO_SLEEP_ENABLE": False,
        "AUTO_SLEEP_WINDOW": 80,
        "AUTO_SLEEP_PCTL": 95,
        "AUTO_SLEEP_MARGIN_SEC": 0.005,
        "AUTO_SLEEP_MIN_SEC": 0.010,
        "AUTO_SLEEP_MAX_SEC": 0.080,
        "AUTO_SLEEP_UPDATE_EVERY": 8,
        "AUTO_SLEEP_PRINT_EVERY_SEC": 5.0,
        "AUTO_SLEEP_NO_RESP_BUMP_SEC": 0.005,
        "AUTO_SLEEP_NO_RESP_STREAK": 2,
        "AUTO_SLEEP_NO_RESP_COOLDOWN_SEC": 0.8,
        "AUTO_SLEEP_DECAY_OK_STREAK": 40,
        "AUTO_SLEEP_DECAY_STEP_SEC": 0.002,
        "RTS_TOGGLE": False,
        "RTS_TX_LEVEL": 1,
        "RTS_RX_LEVEL": 0,
        "RTS_PRE_DELAY_SEC": 0.001,
        "RTS_POST_DELAY_SEC": 0.002,
        "REDIS_RETRY_MIN_SEC": 1.0,
        "REDIS_RETRY_MAX_SEC": 10.0,
        "REDIS_DOWN_PAUSE_SEC": 0.5,
        "SERIAL_RETRY_MIN_SEC": 1.0,
        "SERIAL_RETRY_MAX_SEC": 30.0,
        "SERIAL_RX_ERROR_LIMIT": 5,
        "RX_THREAD_DEAD_REOPEN": True,
        "STALL_WATCHDOG_ENABLE": True,
        "STALL_NOFRAME_SEC": 15.0,
        "STALL_GRACE_AFTER_OPEN_SEC": 2.0,
        "STALL_COOLDOWN_SEC": 15.0,
        "LOG_SEND": False,
        "LOG_RECV_OK": False,
        "LOG_NO_RESP": True,
        "LOG_RX_STATS": True,
        "LOG_MATCH_DETAIL": False,
        "LOG_REDIS_STATE": True,
        "LOG_PORT_STATE": True,
        "STATUS_PRINT_EVERY_SEC": 10.0,
        "MAX_READ_ONCE": 4096,
        "MAX_SOFTBUF": 8192,
        "PENDING_RETRY_ENABLE": True,
        "PENDING_MIN_IDLE_MS": 5000,
        "PENDING_CLAIM_EVERY_SEC": 2.0,
        "PENDING_CLAIM_COUNT": 20,
    },
    "lines": [
        {
            "line_id": 1,
            "name": "Line-1",
            "head_port": "COM3",
            "tail_port": "NONE",
            "baudrate": 19200,
            "timeout": 0.0,
            "devices": make_devices(1, 2),
        },
        {
            "line_id": 2,
            "name": "Line-2",
            "head_port": "COM5",
            "tail_port": "NONE",
            "baudrate": 19200,
            "timeout": 0.0,
            "devices": make_devices(2, 4, nms_offset=2),
        },
    ],
}
