# Generated by Django 5.0.6 on 2025-07-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_analogdata_current_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='depots',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='可管理车间'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
