# Generated by Django 5.0.6 on 2025-11-19 02:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_device_direction1_enabled_device_direction2_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switchdata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'sy状态字快照', 'verbose_name_plural': 'sy状态字快照'},
        ),
        migrations.AddField(
            model_name='device',
            name='direction3_enabled',
            field=models.BooleanField(default=False, verbose_name='三方向启用'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_dynamic_addressing',
            field=models.BooleanField(default=False, verbose_name='启用动态地址派发'),
        ),
        migrations.AddField(
            model_name='device',
            name='manual_address',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='人工指定地址(非0)'),
        ),
        migrations.AddField(
            model_name='device',
            name='sealed_base_addr_bcd',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='上行封连BCD首地址'),
        ),
        migrations.AddField(
            model_name='device',
            name='supports_auto_switch',
            field=models.BooleanField(default=False, verbose_name='具备自动切换功能'),
        ),
        migrations.AddField(
            model_name='switchdata',
            name='version',
            field=models.CharField(choices=[('v4', '4-byte (d1~d4)'), ('v6', '6-byte (legacy)')], default='v4', max_length=4),
        ),
        migrations.AlterField(
            model_name='switchdata',
            name='switch_status',
            field=models.BinaryField(verbose_name='原始状态字节'),
        ),
        migrations.CreateModel(
            name='RemoteControlLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hex', models.CharField(max_length=4, verbose_name='控制码(十六进制字符串)')),
                ('description', models.CharField(max_length=100, verbose_name='含义')),
                ('issued_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='下发人/程序')),
                ('success', models.BooleanField(default=False, verbose_name='执行是否成功')),
                ('reply_raw', models.BinaryField(blank=True, null=True, verbose_name='回执原文')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device', to_field='device_id', verbose_name='设备')),
            ],
            options={
                'verbose_name': '远程控制日志',
                'verbose_name_plural': '远程控制日志',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChangeBitEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bit_index', models.PositiveIntegerField(verbose_name='位序号(0-based, 按 d1~d4 展开共32位)')),
                ('value', models.BooleanField(verbose_name='变为(0/1)')),
                ('source', models.CharField(default='A2', max_length=32, verbose_name='来源')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device', to_field='device_id', verbose_name='设备')),
            ],
            options={
                'verbose_name': '变化量事件',
                'verbose_name_plural': '变化量事件',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='myapp_chang_device__1ecd14_idx')],
            },
        ),
    ]
