# Generated by Django 5.0.6 on 2025-11-20 01:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_switchdata_options_device_direction3_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawFrameLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_frame', models.BinaryField(verbose_name='完整协议帧')),
                ('cmd', models.CharField(blank=True, max_length=4, null=True, verbose_name='命令字')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.device', to_field='device_id', verbose_name='设备')),
            ],
            options={
                'verbose_name': '原始协议帧',
                'verbose_name_plural': '原始协议帧',
                'ordering': ['-timestamp'],
            },
        ),
    ]
