# Generated by Django 5.0.6 on 2025-11-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rawframelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='direction3_neighbor_direction',
            field=models.IntegerField(blank=True, db_index=True, default=1, null=True, verbose_name='三方向邻站方向'),
        ),
        migrations.AddField(
            model_name='device',
            name='direction3_neighbor_id',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='三方向邻站ID'),
        ),
    ]
