# Generated by Django 5.0.6 on 2025-12-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_device_direction3_neighbor_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP地址'),
        ),
    ]
