# Generated by Django 5.0.6 on 2025-12-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_device_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmactive',
            options={'ordering': ['-timestamp_start'], 'verbose_name': '当前告警信息', 'verbose_name_plural': '0 当前告警'},
        ),
        migrations.AlterModelOptions(
            name='alarmdata',
            options={'ordering': ['-timestamp_start'], 'verbose_name': '历史告警记录', 'verbose_name_plural': '1 历史告警'},
        ),
        migrations.AlterModelOptions(
            name='changebitevent',
            options={'ordering': ['-timestamp'], 'verbose_name': '变化量事件', 'verbose_name_plural': '9 变化量事件'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '4 用户'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['device_id'], 'verbose_name': '设备信息', 'verbose_name_plural': '5 设备信息'},
        ),
        migrations.AlterModelOptions(
            name='rawframelog',
            options={'ordering': ['-timestamp'], 'verbose_name': '原始协议帧', 'verbose_name_plural': '7 原始协议帧'},
        ),
        migrations.AlterModelOptions(
            name='relayaction',
            options={'ordering': ['-timestamp'], 'verbose_name': '继电器动作记录', 'verbose_name_plural': '2 继电器动作'},
        ),
        migrations.AlterModelOptions(
            name='switchdata',
            options={'ordering': ['-timestamp'], 'verbose_name': '状态字快照', 'verbose_name_plural': '8 状态字快照'},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-upload_time'], 'verbose_name': '文件', 'verbose_name_plural': '6 文件管理'},
        ),
        migrations.AlterModelOptions(
            name='useroperation',
            options={'ordering': ['-timestamp'], 'verbose_name': '用户操作记录', 'verbose_name_plural': '3 用户操作'},
        ),
        migrations.AlterField(
            model_name='useroperation',
            name='function_code',
            field=models.CharField(max_length=100, verbose_name='操作类型'),
        ),
    ]
