# Generated by Django 5.0.6 on 2026-01-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_alarmactive_options_alter_alarmdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='direction1_cable_alarm_linkage',
            field=models.BooleanField(default=False, verbose_name='一方向电缆告警联动'),
        ),
        migrations.AddField(
            model_name='device',
            name='direction2_cable_alarm_linkage',
            field=models.BooleanField(default=False, verbose_name='二方向电缆告警联动'),
        ),
    ]
