# Generated by Django 5.0.6 on 2026-03-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_add_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alarmdata',
            name='sy_alarmdata_dev_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='analogdata',
            name='sy_analog_dev_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawframelog',
            name='sy_rawframe_dev_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='relayaction',
            name='sy_relay_dev_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='switchdata',
            name='sy_switch_dev_ts_idx',
        ),
    ]
