# Generated by Codex on 2026-03-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_alter_model_verbose_name_plural"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalogData",
        ),
    ]
