# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_finalize_location_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="relayaction",
            name="source",
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name="来源"),
        ),
    ]
